### PR TITLE
fix(wallet-ui): temporary fix for not enough fees

### LINKED ISSUE #1312: bug: indexer sometimes returns too little fees in dry run
**Describe the bug**

bug: indexer sometimes returns too little fees in dry run

**To Reproduce**
1. Transfer confidential finds in wallet
2. Estimate fee and submit
3. Validator returns that too little fees paid (usually by around 3)

**Expected behavior**
Fee estimate is accurate esp if substates are not mutated between calls

**Screenshots**

Image

**Comments**

Additional unit testing of the fee module may be revealing

### PR DESCRIPTION
**Pull request by ksrichard**
Description
---

Closes https://github.com/tari-project/tari-dan/issues/1312

Motivation and Context
---

How Has This Been Tested?
---

What process can a PR reviewer use to test or verify this change?
---

Breaking Changes
---

- [x] None
- [ ] Requires data directory to be deleted
- [ ] Other - Please specify

## Summary by CodeRabbit

- **Bug Fixes**
  - Updated the fee calculation for money transfers to include a temporary adjustment, resulting in more reliable fee estimates during transactions. This update refines your transaction experience by providing clearer fee information at checkout, helping you make more informed decisions when sending money. These enhancements are part of our ongoing effort to improve your overall experience.

- **Style**
  - Improved code formatting and consistency in the WalletConnectLink component for better readability.
  - Streamlined import statements in the SendMoney component for enhanced clarity.

### CODE REVIEW

File: applications/tari_dan_wallet_web_ui/src/routes/AssetVault/Components/SendMoney.tsx [hunk 1]
```diff
@@ -189,7 +189,10 @@ export function SendMoneyDialog(props: SendMoneyDialogProps) {
             });
             return;
           }
-          setTransferFormState({ ...transferFormState, fee: result.fee.toString() });
+          // temporary fix for having a proper calculation for estimated fee to avoid not enough fee issue
+          // TODO: remove once fixed in backend
```
Comment (sdbondi) [inline applications/tari_dan_wallet_web_ui/src/routes/AssetVault/Components/SendMoney.tsx]: This is a bit misleading, it's not a backend bug to be fixed _per se_. The fee calculations are working as intended; the difference in fees is a consequence of the dry run and "normal" transactions differing in an expected way (rangeproof differs in size) causing the fees to differ.
A suggestion to rectify this is to modify the fee calculation to charge a flat fee for withdrawal proof type. Another solution is for the wallet to reuse the rangeproof verbatim (but this may not be possible/desireable when we include the dry run flag in the transaction. See #1376 . However, this is a much simpler solution to this pesky annoyance. 

```suggestion
          // Simple fix for the estimated fee differing between the dry-run and non-dry-run transactions.
          // Since fees are charged for the transaction byte size and for confidential transfers, the rangeproof 
          // may differ in length and, therefore in fees. The fees may differ typically by 2/3, this more than 
          // accounts for that. See https://github.com/tari-project/tari-dan/issues/1312
          // TODO: remove once this is no longer an issue
```

File: applications/tari_dan_wallet_web_ui/src/routes/AssetVault/Components/SendMoney.tsx [hunk 2]
```diff
@@ -189,7 +189,10 @@ export function SendMoneyDialog(props: SendMoneyDialogProps) {
...
+          const fee = (result.fee += 100);
```
Comment (sdbondi) [inline applications/tari_dan_wallet_web_ui/src/routes/AssetVault/Components/SendMoney.tsx]: nit: no need to mutate result type
```suggestion
          const fee = result.fee + 100;
```

**Review by sdbondi — DISMISSED** [review]
LGTM - some nits

**Review by sdbondi — APPROVED** [review]

**Review by sdbondi — APPROVED** [review]
