### PR TITLE
fix(dan)!: update nft address format

### LINKED ISSUE #1080: improve NFT address strings
## Problem

Current address strings are "weird" 

e.g `nft_{resource} int:123` (not the space)

## Proposal 1

`nft_{resource}_type_id `

 e.g. `nft_abdecf123456789..._int_123` `nft_abdecf123456789..._str_kitten99` etc

### PR DESCRIPTION
**Pull request by therealdannzor**
Description
---
Resolves #1080

Motivation and Context
---
Updates the format of the NFT address by removing the blank space between the `resource` and `nft` components

Breaking Changes
---
NFT address format updated

- [ ] None
- [ ] Requires data directory to be deleted
- [X] Other - Please specify

### CODE REVIEW

File: dan_layer/engine_types/src/substate.rs [hunk 1]
```diff
@@ -351,32 +351,39 @@ impl FromStr for SubstateId {
...
-                            ResourceAddress::from_hex(addr).map_err(|_| InvalidSubstateIdFormat(s.to_string()))?;
-                        Ok(SubstateId::Resource(addr))
-                    },
+                if addr.split_once('_').is_none() {
+                    // resource_xxxxx
+                    let addr = ResourceAddress::from_hex(addr).map_err(|_| InvalidSubstateIdFormat(s.to_string()))?;
+                    return Ok(SubstateId::Resource(addr));
+                }
+                let parts = addr.split_once('_').unwrap();
+                let resource_part: Vec<&str> = parts.0.split('_').collect();
```
Comment (sdbondi) [inline dan_layer/engine_types/src/substate.rs]: Generally in string parsing you dont need to allocate on the heap during parsing. `split` and alike return iterators that you can use without first collecting them all in a heap -allocated Vec.

File: dan_layer/engine_types/src/substate.rs [hunk 2]
```diff
@@ -746,19 +753,19 @@ mod tests {
                 .as_resource_address()
                 .unwrap();
             SubstateId::from_str(
-                "resource_7cbfe29101c24924b1b6ccefbfff98986d648622272ae24f7585dab5ffffffff nft_str:SpecialNft",
+                "resource_7cbfe29101c24924b1b6ccefbfff98986d648622272ae24f7585dab5ffffffff_nft_str:SpecialNft",
```
Comment (sdbondi) [inline dan_layer/engine_types/src/substate.rs]: Issue #1080 specifies the format as
`nft_{resource}_{type}_{nft_id}`

Comment (therealdannzor) [reply dan_layer/engine_types/src/substate.rs]: Ok, I wasn't sure since the functions being updated handle multiple types of ID strings. I will make it uniform across the board with this format.

File: dan_layer/engine_types/src/substate.rs [hunk 3]
```diff
@@ -351,33 +351,51 @@ impl FromStr for SubstateId {
...
+                let mut splitted = rest.split('_');
+                let resource_addr: ResourceAddress;
+                if let Some(token) = splitted.next() {
+                    resource_addr =
+                        ResourceAddress::from_hex(token).map_err(|_| InvalidSubstateIdFormat(s.to_string()))?;
+                } else {
+                    return Err(InvalidSubstateIdFormat(
+                        "Missing NFT resource address field".to_string(),
+                    ));
+                }
```
Comment (sdbondi) [inline dan_layer/engine_types/src/substate.rs]: nit: Rust stdlib has a moreidiomatic way of doing this

```suggestion
                let token = splitted.next().ok_or_else(|| InvalidSubstateIdFormat(
                        "Missing NFT resource address field".to_string(),
                    ))?;
                    let resource_addr =
                        ResourceAddress::from_hex(token).map_err(|_| InvalidSubstateIdFormat(s.to_string()))?;
```

Comment (sdbondi) [reply dan_layer/engine_types/src/substate.rs]: Same for below

File: dan_layer/engine_types/src/substate.rs [hunk 4]
```diff
@@ -351,33 +351,51 @@ impl FromStr for SubstateId {
...
-                    },
+                if addr.split_once('_').is_none() {
+                    // resource_xxxxx
+                    let addr = ResourceAddress::from_hex(addr).map_err(|_| InvalidSubstateIdFormat(s.to_string()))?;
+                    return Ok(SubstateId::Resource(addr));
                 }
+                Err(InvalidSubstateIdFormat("Missing resource address".to_string()))
+            },
+            Some(("nft", rest)) => {
+                let mut splitted = rest.split('_');
```
Comment (sdbondi) [inline dan_layer/engine_types/src/substate.rs]: Rather split_once

rest is `{resource_addr}_{type}_{id}`

therefore

```rust
let (resource, nft) = rest.split_once('_').ok_or_else(|| InvalidSubstateIdFormat(
                        s.to_string(),
                    ))?;
    let resource_addr =
                        ResourceAddress::from_hex(resource).map_err(|_| InvalidSubstateIdFormat(s.to_string()))?;

// TODO: nft index should be prefixed with nftindex_{xxxxx} not nft
 let id_type = id.split('_').next().ok_or_else(|| InvalidSubstateIdFormat("Missing NFT id type".to_string()))?
 if id_type == "index" {
                        let index = u64::from_str(token).map_err(|_| InvalidSubstateIdFormat(s.to_string()))?;
                        return Ok(SubstateId::NonFungibleIndex(NonFungibleIndexAddress::new(
                            resource_addr,
                            index,
                        )));
                    }       

let id = NonFungibleId::try_from_canonical_string(nft))
                        .map_err(|_| InvalidSubstateIdFormat(s.to_string()))?;

Comment (sdbondi) [reply dan_layer/engine_types/src/substate.rs]:
```rust
// TODO: nft index should be prefixed with nftindex_{xxxxx} not nft
```
If you're up or doing this TODO as well in this PR feel free.

File: dan_layer/engine_types/src/substate.rs [hunk 5]
```diff
@@ -351,33 +351,45 @@ impl FromStr for SubstateId {
...
-                        let addr =
-                            ResourceAddress::from_hex(addr).map_err(|_| InvalidSubstateIdFormat(s.to_string()))?;
-                        Ok(SubstateId::Resource(addr))
-                    },
+                if addr.split_once('_').is_none() {
+                    // resource_xxxxx
+                    let addr = ResourceAddress::from_hex(addr).map_err(|_| InvalidSubstateIdFormat(s.to_string()))?;
+                    return Ok(SubstateId::Resource(addr));
                 }
+                Err(InvalidSubstateIdFormat("Missing resource address".to_string()))
```
Comment (sdbondi) [inline dan_layer/engine_types/src/substate.rs]: from_hex will already error if addr is malformed. The error "Resource address is missing" doesn't really tell us much. InvalidSubstateIdFormat error type is meant to have the string that we tried to parse in it. e.g. will display `Invalid substate ID "resource_deadbeaf_bad"`. 

```suggestion
                    // resource_xxxxx
                    let addr = ResourceAddress::from_hex(addr).map_err(|_| InvalidSubstateIdFormat(s.to_string()))?;
                    return Ok(SubstateId::Resource(addr));
```

File: dan_layer/engine_types/src/substate.rs [hunk 6]
```diff
@@ -351,33 +351,45 @@ impl FromStr for SubstateId {
...
+
+                let resource_addr =
+                    ResourceAddress::from_hex(resource).map_err(|_| InvalidSubstateIdFormat(s.to_string()))?;
+
+                let (id_type, id) = nft_rest
+                    .split_once('_')
+                    .ok_or_else(|| InvalidSubstateIdFormat(s.to_string()))?;
+
+                let nft_id = NonFungibleId::try_from_canonical_string(&format!("{id_type}_{id}"))
+                    .map_err(|_| InvalidSubstateIdFormat(s.to_string()))?;
```
Comment (sdbondi) [inline dan_layer/engine_types/src/substate.rs]: try_from_canonical_string will already error. There's no need to split and rejoin the string (which allocates a string on the heap)
```suggestion
            let nft_id = NonFungibleId::try_from_canonical_string(nft_rest))
                    .map_err(|_| InvalidSubstateIdFormat(s.to_string()))?;
```

File: dan_layer/template_lib/src/models/non_fungible.rs [hunk 7]
```diff
@@ -133,7 +133,25 @@ impl NonFungibleId {
...
+            return Err(ParseNonFungibleIdError::InvalidFormat);
+        }
+
+        let id: &str;
+        if let Some(token) = splitted.next() {
+            id = token;
+        } else {
+            return Err(ParseNonFungibleIdError::InvalidFormat);
+        }
+
```
Comment (sdbondi) [inline dan_layer/template_lib/src/models/non_fungible.rs]: Rather use

```suggestion
let (id_type, id) = s.split_once('_').ok_or(ParseNonFungibleIdError::InvalidFormat)?;
```

File: dan_layer/template_lib/src/models/non_fungible.rs [hunk 8]
```diff
@@ -263,20 +281,41 @@ impl FromStr for NonFungibleAddress {
...
+        let id: NonFungibleId;
+        if let Some(token) = splitted.next() {
+            id = NonFungibleId::try_from_canonical_string(&format!("{id_type}_{token}"))
+                .map_err(ParseNonFungibleAddressError::InvalidId)?;
+        } else {
+            return Err(ParseNonFungibleAddressError::InvalidFormat);
+        }
+
+        Ok(NonFungibleAddress::new(resource_addr, id))
```
Comment (sdbondi) [inline dan_layer/template_lib/src/models/non_fungible.rs]: Why different parsing code here?

```suggestion
        // the expected format is nft_{resource_hex}_{type}_{id}
let resp = s.strip_prefix("nft_").unwrap_or(s);
 
                let (resource, nft_rest) = rest
                    .split_once('_')
                    .ok_or_else(|| ParseNonFungibleError::InvalidFormat))?;

                let resource_addr =
                    ResourceAddress::from_hex(resource).map_err(|_| InvalidSubstateIdFormat(s.to_string()))?;

                let nft_id = NonFungibleId::try_from_canonical_string(nft_rest))
                    .map_err(|_| InvalidSubstateIdFormat(s.to_string()))?;
                                   

        Ok(NonFungibleAddress::new(resource_addr, nft_id))
```

Then in SubstateId from_str impl - use the above

```rust
NonFungibleAddress::from_str(rest).map_err(...)?;
```

**Review by sdbondi — DISMISSED** [review]

**Review by sdbondi — APPROVED** [review]
